// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnnnagvbrcwwmuglhqjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxubm5hZ3ZicmN3d211Z2xocWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTM1ODQsImV4cCI6MjA1NTU2OTU4NH0.Y5l7yVutPZ0srkdrLM4WPozQibJ90JJGan8TdbEmiNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);